### ISSUE TITLE
Update NPM & OS X Release

### ISSUE THREAD

**Issue by joshgarde** [NodeOS/qemu#4]

**Comment by joshgarde** [comment]
[mac-x64.tar.gz](https://github.com/NodeOS/qemu/files/351905/mac-x64.tar.gz)

**Comment by piranna** [comment]
> mac-x64.tar.gz

Is not this already published on the releases tab? Did Travis give any
timeout problem on this project?

**Comment by joshgarde** [comment]
I don't believe it's published (https://github.com/NodeOS/qemu/releases) and it didn't timeout on Travis.

The platform on the file is wrong though (related pull request: https://github.com/NodeOS/qemu/releases).

**Comment by piranna** [comment]
I have just published it by hand. Do you have Travis working? Maybe I could enable it now...
